name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check AWS Secret
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "❌ SECRET NOT FOUND"
            exit 1
          else
            echo "✅ SECRET FOUND"
          fi
